export RSATPATH=/media/sf_RSAT/source
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/SafetyMetrics
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/SafetyMetrics/sheltering
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/BlastOverpressure
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/DebrisCatalog
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/GasDispersion
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/InverseProblem
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/STATS
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/TrajectoryPropagation
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/TrajectoryPropagation/PythonScripts
export PYTHONPATH
