export RSATPATH=/Users/fcapristan/Documents/SVNhard_drive/ALL_TOOLS/RSAT/source
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/SafetyMetrics
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/SafetyMetrics/sheltering
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/BlastOverpressure
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/DebrisCatalog
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/GasDispersion
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/InverseProblem
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/STATS
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/TrajectoryPropagation
PYTHONPATH=${PYTHONPATH}:${RSATPATH}/TrajectoryPropagation/PythonScripts
export PYTHONPATH
